name: Continuous deployment

on: [pull_request, issues]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      POSTGRES_USER: ${{secrets.keys.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.keys.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.keys.POSTGRES_DB}}

    steps:
    - uses: actions/checkout@main
    - name: docker compose build
      run: docker-compose up --build

    - name: test
      run: python3 -v
