name: Continuous deployment

on: [pull_request, issues]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: docker compose build
      run: docker-compose up --build ../../docker-compose.yml

    - name: test
      run: python3 -v
