name: Continuous deployment

on: [pull_request, issues]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: build
      run: docker-compose -f ../../docker-compose.yml

    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest test_elearning.py
