name: Continuous deployment

on: [pull_request, issues]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: build
      run: docker-compose -f ../../docker-compose.yml

    - name: test
      run: python test_elearning.py
